### ISSUE TITLE
Error in Linux - No module named 'mido'

### ISSUE THREAD

**Issue by jurassicjordan** [EmuMan44/blender-midi-utils#1]
This is after installing mido via terminal.

Traceback (most recent call last):
  File "/var/lib/snapd/snap/blender/2474/3.2/scripts/modules/addon_utils.py", line 335, in enable
    mod = __import__(module_name)
  File "/home/jordancruz/.config/blender/3.2/scripts/addons/blender-midi-utils-master/__init__.py", line 31, in <module>
    from .utils import MidiKeyframes, add_keyboard
  File "/home/jordancruz/.config/blender/3.2/scripts/addons/blender-midi-utils-master/utils.py", line 2, in <module>
    import mido
ModuleNotFoundError: No module named 'mido'

OS: EndeavourOS
Python: 3.10
Blender: 3.2.0

**Comment by jurassicjordan** [comment]
Found the issue. It was blender being in a sandboxed snap that didn't give access to the allow access to the system's python environment.
